<?php
/**
 * Top menu for store
 *
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>

<!-- navigation BOF -->

<?php $_menu_mobile = $this->renderCategoriesMenuHtml(0, 'level-top' ) ?>
<?php if($_menu_mobile): ?>
<div class="mobile-nav">
	<div class="nav-container">
		<div class="nav-top-title"><div class="icon"><span></span><span></span><span></span></div><?php echo $this->__('Navigation'); ?></div>
	    <ul id="mobile-nav">
	        <?php if (Mage::getStoreConfig('sofiadesign/navigation/home')): ?>
	        <li class="level0 level-top">
	            <a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home'); ?></span></a>
	        </li>
	        <?php endif; ?>
	        <?php
	        echo $_menu_mobile;
	        $custom_tab = Mage::getModel('cms/block')->load('ft001_navigation_block');
	        if($custom_tab->getIsActive()) {
	            echo '
	            <li class="level0 level-top parent custom-block">
	                <a href="#" class="level-top">
	                    <span>'.$custom_tab->getTitle().'</span>
	                </a>
	                <ul><li style="width:'.Mage::getStoreConfig('sofiadesign/navigation/custom_block_width').'px" >'.$this->getLayout()->createBlock('cms/block')->setBlockId('ft001_navigation_block')->toHtml().'</li></ul>
	            </li>';
	        }
	        ?>
	    </ul>
	</div>
</div>
<?php endif ?>

<?php $_menu = $this->renderCategoriesMenuHtml(0, 'level-top', 'sub-wrapper' ) ?>
<?php if($_menu): ?>
<div class="navigation clearfix">
    <ul id="mainNav">
	    <?php if (Mage::getStoreConfig('sofiadesign/navigation/home')): ?>
         <li class="home level0 level-top <?php if (Mage::helper('core/url')->getCurrentUrl() === Mage::helper('core/url')->getHomeUrl()):?>active<?php endif;?>">
         	<a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home'); ?></span></a>
         </li>
     <?php endif; ?>
        <?php
        
       echo $_menu;
        
        $custom_tab = Mage::getModel('cms/block')->load('ft001_navigation_block');
        if($custom_tab->getIsActive()) {
            echo '
            <li class="level0 level-top parent custom-block">
                <a href="#" class="level-top">
                    <span>'.$custom_tab->getTitle().'</span>
                </a>
                <div class="sub-wrapper" style="width:'.Mage::getStoreConfig('sofiadesign/navigation/custom_block_width').'px">'.$this->getLayout()->createBlock('cms/block')->setBlockId('ft001_navigation_block')->toHtml().'</div>
            </li>';
        }
        ?>
    </ul>
</div>
<?php endif ?>
<!-- navigation EOF -->