<?php
$bannerCollection = $this->getBannerCollection();
?>

<?php $timeDelay = $this->getDelayTime() ?>
<?php $showdesc = $this->isShowDescription() ?>
<?php //$listStyle = $this->getListStyle() ?>
<?php $imagewidth = $this->getImageWidth() ?>
<?php $imageheight = $this->getImageHeight() ?>

<?php if (count($bannerCollection)): ?>
<div class = 'slideshow-container'>
	<div class='iosSlider'>
		<div class='slider'>
		<?php $i = 0; foreach ($bannerCollection as $banner): $i++; ?>
			<div class='item' id='item1'>
				<div class = 'inner'>
					<?php if($banner['weblink']):?>
					<a href="<?php echo $banner['weblink'];?>">
					<?php endif;?>
					
					<img class="image-item" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" />
					<?php if($banner['weblink']):?>
					</a>
					<?php endif;?>
														
					<?php if($banner['content']): ?>
						<div class="description">
							<span><?php echo $banner['content']; ?></span>
						</div>
					<?php endif; ?>
					
					<?php //echo $banner['content']; ?>
				</div>
			</div>
		<?php endforeach; ?>
		</div>
	</div>
			<div class="next" style="cursor: pointer;"></div>
			<div class="prev" style="cursor: pointer;"></div>
</div>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/iosslider.css');?>" media="all" />


<script type="text/javascript" src="<?php echo $this->getJsUrl('bannerslider/jquery-1.4.2.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('bannerslider/jquery-easing-1.3.pack.js') ?>"></script>

<script type="text/javascript">
	jQuery.noConflict(); 
</script>

<script type="text/javascript" src="<?php echo $this->getJsUrl('bannerslider/jquery.iosslider.min.js') ?>"></script>
		<script type="text/javascript">
		jQuery(document).ready(function() {
				
			jQuery('.iosSlider').iosSlider({
					desktopClickDrag: true,
					snapToChildren: true,
					navSlideSelector: '.sliderContainer .slideSelectors .item',
					autoSlide: true,
					navNextSelector: jQuery('.next'),
					navPrevSelector: jQuery('.prev'),
					infiniteSlider: true
				});
				
			});
			
		</script>

<?php endif; ?>

<div class="clear"></div>


<?php 
		$collection_of_products = Mage::getModel('catalog/product')->getCollection();
		//var_dump($collection_of_products->getSelect()); //might cause a segmentation fault
		var_dump(
		(string) $collection_of_products->getSelect()
		);
		
		//var_dump( $this->getDume());
		
		//echo $this->getImageHeight();
?>


